# permissions for end users to view ghactions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ghaction-viewer-role
rules:
- apiGroups:
  - githubaction.thenullchannel.dev
  resources:
  - ghactions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - githubaction.thenullchannel.dev
  resources:
  - ghactions/status
  verbs:
  - get
