# permissions for end users to edit texts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: text-editor-role
rules:
- apiGroups:
  - kubetext.thenullchannel.dev
  resources:
  - texts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubetext.thenullchannel.dev
  resources:
  - texts/status
  verbs:
  - get
