# permissions for end users to edit emails.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-editor-role
rules:
- apiGroups:
  - nullemail.thenullchannel.dev
  resources:
  - emails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nullemail.thenullchannel.dev
  resources:
  - emails/status
  verbs:
  - get
