# permissions for end users to view labelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeler-viewer-role
rules:
- apiGroups:
  - nulllabeler.thenullchannel.dev
  resources:
  - labelers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nulllabeler.thenullchannel.dev
  resources:
  - labelers/status
  verbs:
  - get
