# permissions for end users to edit labelers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labeler-editor-role
rules:
- apiGroups:
  - nulllabeler.thenullchannel.dev
  resources:
  - labelers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nulllabeler.thenullchannel.dev
  resources:
  - labelers/status
  verbs:
  - get
